//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languaging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fnb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fnb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languaging.Resources.fnb", typeof(Resources_fnb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Failed Count.
        /// </summary>
        public static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Indicator.
        /// </summary>
        public static string ActiveIndicator {
            get {
                return ResourceManager.GetString("ActiveIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address I D.
        /// </summary>
        public static string AddressID {
            get {
                return ResourceManager.GetString("AddressID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 1.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 3.
        /// </summary>
        public static string AddressLine3 {
            get {
                return ResourceManager.GetString("AddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;adresse.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Group.
        /// </summary>
        public static string AgeGroup {
            get {
                return ResourceManager.GetString("AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A S P User Id.
        /// </summary>
        public static string ASPUserId {
            get {
                return ResourceManager.GetString("ASPUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailableSOH.
        /// </summary>
        public static string AvailableSOH {
            get {
                return ResourceManager.GetString("AvailableSOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Detail Account Number.
        /// </summary>
        public static string BankingDetailAccountNumber {
            get {
                return ResourceManager.GetString("BankingDetailAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Detail Account Type.
        /// </summary>
        public static string BankingDetailAccountType {
            get {
                return ResourceManager.GetString("BankingDetailAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Detail Bank.
        /// </summary>
        public static string BankingDetailBank {
            get {
                return ResourceManager.GetString("BankingDetailBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Detail Branch Code.
        /// </summary>
        public static string BankingDetailBranchCode {
            get {
                return ResourceManager.GetString("BankingDetailBranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Detail Branch Name.
        /// </summary>
        public static string BankingDetailBranchName {
            get {
                return ResourceManager.GetString("BankingDetailBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Detail Default Reference.
        /// </summary>
        public static string BankingDetailDefaultReference {
            get {
                return ResourceManager.GetString("BankingDetailDefaultReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Game Rule I D.
        /// </summary>
        public static string ChainGameRuleID {
            get {
                return ResourceManager.GetString("ChainGameRuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Value.
        /// </summary>
        public static string ClaimValue {
            get {
                return ResourceManager.GetString("ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Code.
        /// </summary>
        public static string ContractCode {
            get {
                return ResourceManager.GetString("ContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Detail.
        /// </summary>
        public static string ContractDetail {
            get {
                return ResourceManager.GetString("ContractDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract I D.
        /// </summary>
        public static string ContractID {
            get {
                return ResourceManager.GetString("ContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country I D.
        /// </summary>
        public static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Inserted.
        /// </summary>
        public static string DateInserted {
            get {
                return ResourceManager.GetString("DateInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Updated.
        /// </summary>
        public static string DateUpdated {
            get {
                return ResourceManager.GetString("DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Used.
        /// </summary>
        public static string DateUsed {
            get {
                return ResourceManager.GetString("DateUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definition.
        /// </summary>
        public static string definition {
            get {
                return ResourceManager.GetString("definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete On Save.
        /// </summary>
        public static string DeleteOnSave {
            get {
                return ResourceManager.GetString("DeleteOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Agent Name.
        /// </summary>
        public static string DeliveryAgentName {
            get {
                return ResourceManager.GetString("DeliveryAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Agent Reference Number.
        /// </summary>
        public static string DeliveryAgentReferenceNumber {
            get {
                return ResourceManager.GetString("DeliveryAgentReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diagram_id.
        /// </summary>
        public static string diagram_id {
            get {
                return ResourceManager.GetString("diagram_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Item I D.
        /// </summary>
        public static string DisplayItemID {
            get {
                return ResourceManager.GetString("DisplayItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Item Type.
        /// </summary>
        public static string DisplayItemType {
            get {
                return ResourceManager.GetString("DisplayItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Item U R L.
        /// </summary>
        public static string DisplayItemURL {
            get {
                return ResourceManager.GetString("DisplayItemURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string Ethnicity {
            get {
                return ResourceManager.GetString("Ethnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code.
        /// </summary>
        public static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Description.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event I D.
        /// </summary>
        public static string EventID {
            get {
                return ResourceManager.GetString("EventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Indicator.
        /// </summary>
        public static string ExclusiveIndicator {
            get {
                return ResourceManager.GetString("ExclusiveIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Criteria.
        /// </summary>
        public static string FilterCriteria {
            get {
                return ResourceManager.GetString("FilterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Code.
        /// </summary>
        public static string GameCode {
            get {
                return ResourceManager.GetString("GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Description.
        /// </summary>
        public static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game I D.
        /// </summary>
        public static string GameID {
            get {
                return ResourceManager.GetString("GameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rule Code.
        /// </summary>
        public static string GameRuleCode {
            get {
                return ResourceManager.GetString("GameRuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rule Detail.
        /// </summary>
        public static string GameRuleDetail {
            get {
                return ResourceManager.GetString("GameRuleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rule I D.
        /// </summary>
        public static string GameRuleID {
            get {
                return ResourceManager.GetString("GameRuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Schedule Code.
        /// </summary>
        public static string GameScheduleCode {
            get {
                return ResourceManager.GetString("GameScheduleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Schedule I D.
        /// </summary>
        public static string GameScheduleID {
            get {
                return ResourceManager.GetString("GameScheduleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Template Code.
        /// </summary>
        public static string GameTemplateCode {
            get {
                return ResourceManager.GetString("GameTemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Template I D.
        /// </summary>
        public static string GameTemplateID {
            get {
                return ResourceManager.GetString("GameTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type Code.
        /// </summary>
        public static string GameTypeCode {
            get {
                return ResourceManager.GetString("GameTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type Description.
        /// </summary>
        public static string GameTypeDescription {
            get {
                return ResourceManager.GetString("GameTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type I D.
        /// </summary>
        public static string GameTypeID {
            get {
                return ResourceManager.GetString("GameTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type Name.
        /// </summary>
        public static string GameTypeName {
            get {
                return ResourceManager.GetString("GameTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type Owned Code.
        /// </summary>
        public static string GameTypeOwnedCode {
            get {
                return ResourceManager.GetString("GameTypeOwnedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type Owned I D.
        /// </summary>
        public static string GameTypeOwnedID {
            get {
                return ResourceManager.GetString("GameTypeOwnedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNB English .
        /// </summary>
        public static string HomePageSubHeader1 {
            get {
                return ResourceManager.GetString("HomePageSubHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words in a box that FNB might use.
        /// </summary>
        public static string HomePageSubHeader1Content {
            get {
                return ResourceManager.GetString("HomePageSubHeader1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More FNB Words.
        /// </summary>
        public static string HomePageSubHeader2 {
            get {
                return ResourceManager.GetString("HomePageSubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNB.
        /// </summary>
        public static string HomePageSubHeader2Content {
            get {
                return ResourceManager.GetString("HomePageSubHeader2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yet more FNB words.
        /// </summary>
        public static string HomePageSubHeader3 {
            get {
                return ResourceManager.GetString("HomePageSubHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNBFNB.
        /// </summary>
        public static string HomePageSubHeader3Content {
            get {
                return ResourceManager.GetString("HomePageSubHeader3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Type.
        /// </summary>
        public static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Type Code.
        /// </summary>
        public static string InteractionTypeCode {
            get {
                return ResourceManager.GetString("InteractionTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Type Description.
        /// </summary>
        public static string InteractionTypeDescription {
            get {
                return ResourceManager.GetString("InteractionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Type I D.
        /// </summary>
        public static string InteractionTypeID {
            get {
                return ResourceManager.GetString("InteractionTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Type Name.
        /// </summary>
        public static string InteractionTypeName {
            get {
                return ResourceManager.GetString("InteractionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I P Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsExclusive.
        /// </summary>
        public static string IsExclusive {
            get {
                return ResourceManager.GetString("IsExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout Enabled.
        /// </summary>
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout End Date Utc.
        /// </summary>
        public static string LockoutEndDateUtc {
            get {
                return ResourceManager.GetString("LockoutEndDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Provider.
        /// </summary>
        public static string LoginProvider {
            get {
                return ResourceManager.GetString("LoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Acquisition Campaign Code.
        /// </summary>
        public static string MemberAcquisitionCampaignCode {
            get {
                return ResourceManager.GetString("MemberAcquisitionCampaignCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Acquisition Campaign Description.
        /// </summary>
        public static string MemberAcquisitionCampaignDescription {
            get {
                return ResourceManager.GetString("MemberAcquisitionCampaignDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Acquisition Campaign I D.
        /// </summary>
        public static string MemberAcquisitionCampaignID {
            get {
                return ResourceManager.GetString("MemberAcquisitionCampaignID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Acquisition Campaign Name.
        /// </summary>
        public static string MemberAcquisitionCampaignName {
            get {
                return ResourceManager.GetString("MemberAcquisitionCampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member At Event I D.
        /// </summary>
        public static string MemberAtEventID {
            get {
                return ResourceManager.GetString("MemberAtEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member I D.
        /// </summary>
        public static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member In Game I D.
        /// </summary>
        public static string MemberInGameID {
            get {
                return ResourceManager.GetString("MemberInGameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Interest I D.
        /// </summary>
        public static string MemberInterestID {
            get {
                return ResourceManager.GetString("MemberInterestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Owned I D.
        /// </summary>
        public static string MemberOwnedID {
            get {
                return ResourceManager.GetString("MemberOwnedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Subscription Type Code.
        /// </summary>
        public static string MemberSubscriptionTypeCode {
            get {
                return ResourceManager.GetString("MemberSubscriptionTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Subscription Type Description.
        /// </summary>
        public static string MemberSubscriptionTypeDescription {
            get {
                return ResourceManager.GetString("MemberSubscriptionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Subscription Type I D.
        /// </summary>
        public static string MemberSubscriptionTypeID {
            get {
                return ResourceManager.GetString("MemberSubscriptionTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Game I D.
        /// </summary>
        public static string NextGameID {
            get {
                return ResourceManager.GetString("NextGameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Code.
        /// </summary>
        public static string OwnerCode {
            get {
                return ResourceManager.GetString("OwnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner I D.
        /// </summary>
        public static string OwnerID {
            get {
                return ResourceManager.GetString("OwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Type.
        /// </summary>
        public static string OwnerType {
            get {
                return ResourceManager.GetString("OwnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Hash.
        /// </summary>
        public static string PasswordHash {
            get {
                return ResourceManager.GetString("PasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Confirmed.
        /// </summary>
        public static string PhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Coordinates.
        /// </summary>
        public static string PhysicalCoordinates {
            get {
                return ResourceManager.GetString("PhysicalCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to principal_id.
        /// </summary>
        public static string principal_id {
            get {
                return ResourceManager.GetString("principal_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category Code.
        /// </summary>
        public static string ProductCategoryCode {
            get {
                return ResourceManager.GetString("ProductCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category Description.
        /// </summary>
        public static string ProductCategoryDescription {
            get {
                return ResourceManager.GetString("ProductCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category I D.
        /// </summary>
        public static string ProductCategoryID {
            get {
                return ResourceManager.GetString("ProductCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category Name.
        /// </summary>
        public static string ProductCategoryName {
            get {
                return ResourceManager.GetString("ProductCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product I D.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product In Category I D.
        /// </summary>
        public static string ProductInCategoryID {
            get {
                return ResourceManager.GetString("ProductInCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product In Game I D.
        /// </summary>
        public static string ProductInGameID {
            get {
                return ResourceManager.GetString("ProductInGameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product In Watch List I D.
        /// </summary>
        public static string ProductInWatchListID {
            get {
                return ResourceManager.GetString("ProductInWatchListID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Location I D.
        /// </summary>
        public static string ProductLocationID {
            get {
                return ResourceManager.GetString("ProductLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Played I D.
        /// </summary>
        public static string ProductPlayedID {
            get {
                return ResourceManager.GetString("ProductPlayedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product S K U Code.
        /// </summary>
        public static string ProductSKUCode {
            get {
                return ResourceManager.GetString("ProductSKUCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Key.
        /// </summary>
        public static string ProviderKey {
            get {
                return ResourceManager.GetString("ProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Date.
        /// </summary>
        public static string RenewalDate {
            get {
                return ResourceManager.GetString("RenewalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Date Time.
        /// </summary>
        public static string ScheduledDateTime {
            get {
                return ResourceManager.GetString("ScheduledDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Stamp.
        /// </summary>
        public static string SecurityStamp {
            get {
                return ResourceManager.GetString("SecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number I D.
        /// </summary>
        public static string SerialNumberID {
            get {
                return ResourceManager.GetString("SerialNumberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French for Stock on Hand.
        /// </summary>
        public static string SOH {
            get {
                return ResourceManager.GetString("SOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State I D.
        /// </summary>
        public static string StateID {
            get {
                return ResourceManager.GetString("StateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Or Province.
        /// </summary>
        public static string StateOrProvince {
            get {
                return ResourceManager.GetString("StateOrProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Home.
        /// </summary>
        public static string TelephoneHome {
            get {
                return ResourceManager.GetString("TelephoneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Mobile.
        /// </summary>
        public static string TelephoneMobile {
            get {
                return ResourceManager.GetString("TelephoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Office.
        /// </summary>
        public static string TelephoneOffice {
            get {
                return ResourceManager.GetString("TelephoneOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Code.
        /// </summary>
        public static string TerritoryCode {
            get {
                return ResourceManager.GetString("TerritoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Definition Code.
        /// </summary>
        public static string TerritoryDefinitionCode {
            get {
                return ResourceManager.GetString("TerritoryDefinitionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Definition I D.
        /// </summary>
        public static string TerritoryDefinitionID {
            get {
                return ResourceManager.GetString("TerritoryDefinitionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Description.
        /// </summary>
        public static string TerritoryDescription {
            get {
                return ResourceManager.GetString("TerritoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory I D.
        /// </summary>
        public static string TerritoryID {
            get {
                return ResourceManager.GetString("TerritoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Name.
        /// </summary>
        public static string TerritoryName {
            get {
                return ResourceManager.GetString("TerritoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Enabled.
        /// </summary>
        public static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U S R.
        /// </summary>
        public static string USR {
            get {
                return ResourceManager.GetString("USR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher I D.
        /// </summary>
        public static string VoucherID {
            get {
                return ResourceManager.GetString("VoucherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Number.
        /// </summary>
        public static string VoucherNumber {
            get {
                return ResourceManager.GetString("VoucherNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Interaction I D.
        /// </summary>
        public static string WebsiteInteractionID {
            get {
                return ResourceManager.GetString("WebsiteInteractionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Or Postal Code.
        /// </summary>
        public static string ZipOrPostalCode {
            get {
                return ResourceManager.GetString("ZipOrPostalCode", resourceCulture);
            }
        }
    }
}
