//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryStates = new HashSet<CountryState>();
            this.Currencies = new HashSet<Currency>();
            this.Members = new HashSet<Member>();
            this.CountryCities = new HashSet<CountryCity>();
            this.TerritoryDefinitions = new HashSet<TerritoryDefinition>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<CountryState> CountryStates { get; set; }
        public virtual ICollection<Currency> Currencies { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<CountryCity> CountryCities { get; set; }
        public virtual ICollection<TerritoryDefinition> TerritoryDefinitions { get; set; }
    }
}
