//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryState
    {
        public CountryState()
        {
            this.Members = new HashSet<Member>();
            this.CountryCities = new HashSet<CountryCity>();
            this.TerritoryDefinitions = new HashSet<TerritoryDefinition>();
        }
    
        public int StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<CountryCity> CountryCities { get; set; }
        public virtual ICollection<TerritoryDefinition> TerritoryDefinitions { get; set; }
    }
}
