//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Owners = new HashSet<Owner>();
            this.ProductInGames = new HashSet<ProductInGame>();
        }
    
        public int CurrencyID { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
        public virtual ICollection<ProductInGame> ProductInGames { get; set; }
    }
}
