//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.EmailErrorLogs = new HashSet<EmailErrorLog>();
            this.EmailSendLogs = new HashSet<EmailSendLog>();
        }
    
        public long EmailID { get; set; }
        public string Status { get; set; }
        public int Priority { get; set; }
        public System.DateTime SendAfter { get; set; }
        public int Attempts { get; set; }
        public bool FailedPermanently { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public string RecipientEmailAddress { get; set; }
        public string RecipientName { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBodyText { get; set; }
        public string FromAddress { get; set; }
        public string FromName { get; set; }
        public int MemberID { get; set; }
    
        public virtual ICollection<EmailErrorLog> EmailErrorLogs { get; set; }
        public virtual ICollection<EmailSendLog> EmailSendLogs { get; set; }
    }
}
