//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public int ConfigID { get; set; }
        public string ConfigDescription { get; set; }
        public string Status { get; set; }
        public System.DateTime DateInserted { get; set; }
        public string DefaultFromName { get; set; }
        public string DefaultFromAddress { get; set; }
        public string smtpUsername { get; set; }
        public string smtpPassword { get; set; }
        public string smtpServerURI { get; set; }
        public Nullable<bool> smtpEnableSSL { get; set; }
        public Nullable<int> DefaultMaxRetries { get; set; }
        public string smtpServerPort { get; set; }
    }
}
