//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRule
    {
        public int GameRuleID { get; set; }
        public string GameRuleCode { get; set; }
        public int GameID { get; set; }
        public string FilterCriteria { get; set; }
        public int Schedule { get; set; }
        public Nullable<int> ChainGameRuleID { get; set; }
        public string GameRuleDetail { get; set; }
        public System.DateTime ExcecuteTime { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public int GameTemplateID { get; set; }
        public string ExecuteHhMmSs { get; set; }
    
        public virtual GameTemplate GameTemplate { get; set; }
        public virtual Game Game { get; set; }
    }
}
