//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.LanguageItems = new HashSet<LanguageItem>();
            this.DisplayItems = new HashSet<DisplayItem>();
        }
    
        public int LanguageID { get; set; }
        public string LanguageName { get; set; }
        public string LanguageTwoLetters { get; set; }
        public string LanguageThreeLetters { get; set; }
    
        public virtual ICollection<LanguageItem> LanguageItems { get; set; }
        public virtual ICollection<DisplayItem> DisplayItems { get; set; }
    }
}
