//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInterest
    {
        public int MemberInterestID { get; set; }
        public int MemberID { get; set; }
        public int ProductCategoryID { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public bool MemberInterestAutomotive { get; set; }
        public bool MemberInterestArtCollectibles { get; set; }
        public bool MemberInterestHomeAppliances { get; set; }
        public bool MemberInterestToys { get; set; }
        public bool MemberInterestEntertainment { get; set; }
        public bool MemberInterestDecorDesign { get; set; }
        public bool MemberInterestHealthBeauty { get; set; }
        public bool MemberInterestTravel { get; set; }
        public bool MemberInterestFashionAccessories { get; set; }
        public bool MemberInterestExperiences { get; set; }
        public bool MemberInterestTechnology { get; set; }
        public bool MemberInterestWiningDining { get; set; }
        public string MemberInterestOther { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
