//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAcquisitionCampaign
    {
        public MemberAcquisitionCampaign()
        {
            this.MemberOwneds = new HashSet<MemberOwned>();
        }
    
        public int MemberAcquisitionCampaignID { get; set; }
        public string MemberAcquisitionCampaignCode { get; set; }
        public int OwnerID { get; set; }
        public int ContractID { get; set; }
        public string MemberAcquisitionCampaignName { get; set; }
        public string MemberAcquisitionCampaignDescription { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<MemberOwned> MemberOwneds { get; set; }
    }
}
