//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberAtEvents = new HashSet<MemberAtEvent>();
            this.MemberInGames = new HashSet<MemberInGame>();
            this.MemberInterests = new HashSet<MemberInterest>();
            this.MemberOwneds = new HashSet<MemberOwned>();
            this.ProductInWatchLists = new HashSet<ProductInWatchList>();
            this.WebsiteInteractions = new HashSet<WebsiteInteraction>();
            this.GameInteractions = new HashSet<GameInteraction>();
        }
    
        public int MemberID { get; set; }
        public int MemberSubscriptionTypeID { get; set; }
        public string IdentityType { get; set; }
        public string EmailAddress { get; set; }
        public string TelephoneHome { get; set; }
        public string TelephoneOffice { get; set; }
        public string TelephoneMobile { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool ActiveIndicator { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<int> AddressID { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public string ASPUserId { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberAcquisitionCampaignCode { get; set; }
        public Nullable<int> CityID { get; set; }
        public string IdentityNumber { get; set; }
        public string Industry { get; set; }
        public string Designation { get; set; }
        public string MaritalStatus { get; set; }
        public string Children { get; set; }
        public Nullable<int> OwnerID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CountryState CountryState { get; set; }
        public virtual MemberSubscriptionType MemberSubscriptionType { get; set; }
        public virtual ICollection<MemberAtEvent> MemberAtEvents { get; set; }
        public virtual ICollection<MemberInGame> MemberInGames { get; set; }
        public virtual ICollection<MemberInterest> MemberInterests { get; set; }
        public virtual ICollection<MemberOwned> MemberOwneds { get; set; }
        public virtual ICollection<ProductInWatchList> ProductInWatchLists { get; set; }
        public virtual ICollection<WebsiteInteraction> WebsiteInteractions { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<GameInteraction> GameInteractions { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
