//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSubscriptionType
    {
        public MemberSubscriptionType()
        {
            this.Members = new HashSet<Member>();
            this.Games = new HashSet<Game>();
        }
    
        public int MemberSubscriptionTypeID { get; set; }
        public string MemberSubscriptionTypeCode { get; set; }
        public string MemberSubscriptionTypeDescription { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public decimal amount { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Game> Games { get; set; }
    }
}
