//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int PaymentTransactionID { get; set; }
        public Nullable<int> MemberInGameID { get; set; }
        public string Action { get; set; }
        public string Member { get; set; }
        public string CurrencyCode { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string Zip { get; set; }
        public string CountryCode { get; set; }
        public string email { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TrackID { get; set; }
        public string MerchantIP { get; set; }
        public string ClientIP { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string Result { get; set; }
        public string ResponseCode { get; set; }
        public string AuthCode { get; set; }
        public string TranID { get; set; }
        public Nullable<System.DateTime> TransactionRequestDateTime { get; set; }
        public Nullable<System.DateTime> TransactionResponseDateTime { get; set; }
        public string PaymentStatus { get; set; }
        public string State { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
    
        public virtual MemberInGame MemberInGame { get; set; }
    }
}
