//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayableGamesByMember
    {
        public string GameName { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> PriceInGame { get; set; }
        public string DisplayItemType { get; set; }
        public string DisplayItemURL { get; set; }
        public bool Active { get; set; }
        public int MemberID { get; set; }
        public int GameID { get; set; }
        public string GameState { get; set; }
    }
}
