//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLocation
    {
        public ProductLocation()
        {
            this.SerialNumbers = new HashSet<SerialNumber>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int ProductLocationID { get; set; }
        public int ProductInGameID { get; set; }
        public string Address { get; set; }
        public string DeliveryAgentName { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
    
        public virtual ICollection<SerialNumber> SerialNumbers { get; set; }
        public virtual ICollection<Voucher> Vouchers { get; set; }
        public virtual ProductInGame ProductInGame { get; set; }
    }
}
