//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowWinner
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public string GameDescription { get; set; }
        public string GameState { get; set; }
        public int MemberID { get; set; }
        public bool WinIndicator { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string TelephoneHome { get; set; }
        public string TelephoneMobile { get; set; }
        public System.DateTime ExcecuteTime { get; set; }
        public bool paymentIndicator { get; set; }
    }
}
