//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultLifeAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VoucherID { get; set; }
        public string VoucherNumber { get; set; }
        public int ProductLocationID { get; set; }
        public bool Used { get; set; }
        public System.DateTime DateInserted { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
    
        public virtual ProductLocation ProductLocation { get; set; }
    }
}
