//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayItem
    {
        public int DisplayItemID { get; set; }
        public int ProductID { get; set; }
        public string DisplayItemType { get; set; }
        public string DisplayItemURL { get; set; }
        public bool Active { get; set; }
        public bool DeleteOnSave { get; set; }
        public Nullable<int> LanguageID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Language Language { get; set; }
    }
}
