//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedProductInWatchList
    {
        public int ProductInWatchListID { get; set; }
        public int MemberID { get; set; }
        public int ProductID { get; set; }
        public int GameID { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public System.DateTime ExcecuteTime { get; set; }
        public string ExecuteHhMmSs { get; set; }
    }
}
