//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameMemberFilter
    {
        public int GameMemberFilterID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AgeBandID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> Territory { get; set; }
        public Nullable<int> MemberSubscriptionTypeID { get; set; }
    }
}
