//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberOwned
    {
        public int MemberOwnedID { get; set; }
        public int MemberID { get; set; }
        public int OwnerID { get; set; }
        public int TerritoryID { get; set; }
        public int MemberAcquisitionCampaignID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public bool ExclusiveIndicator { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MemberAcquisitionCampaign MemberAcquisitionCampaign { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
