//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPlayed
    {
        public int ProductPlayedID { get; set; }
        public Nullable<int> ProductInGameID { get; set; }
        public Nullable<int> MemberInGameID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> SerialNumberID { get; set; }
        public string DeliveryAgentName { get; set; }
        public string DeliveryAgentReferenceNumber { get; set; }
        public Nullable<int> ClickInterval { get; set; }
        public int Winner { get; set; }
        public Nullable<System.DateTime> PaymentConfirmed { get; set; }
        public Nullable<System.DateTime> DateInserted { get; set; }
    
        public virtual ProductInGame ProductInGame { get; set; }
        public virtual MemberInGame MemberInGame { get; set; }
    }
}
