//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInGame
    {
        public ProductInGame()
        {
            this.ProductLocations = new HashSet<ProductLocation>();
            this.ProductPlayeds = new HashSet<ProductPlayed>();
        }
    
        public int ProductInGameID { get; set; }
        public int ProductID { get; set; }
        public int GameID { get; set; }
        public int Quantity { get; set; }
        public int CurrencyID { get; set; }
        public System.DateTime DateInserted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string USR { get; set; }
        public Nullable<decimal> PriceInGame { get; set; }
        public Nullable<decimal> ReferencePrice { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductLocation> ProductLocations { get; set; }
        public virtual ICollection<ProductPlayed> ProductPlayeds { get; set; }
        public virtual Game Game { get; set; }
    }
}
