//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace Vaultlife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerConfig
    {
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public string ServerIp { get; set; }
        public Uri RequestUrl { get; set; }
    }
}
